site_name: Diego Marini
site_url: https://marini.work

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.footer

nav:
  - Home: index.md
  - Appunti:
      - Geometria: geometria/index.md
      - Fisica 1: fisica/index.md
      - Fondamenti: fondamenti/index.md
  - Problem Solving: problem-solving.md
  - Progetti: projects.md
  - About: about.md

extra_css:
  - stylesheets/typewriter.css

plugins:
  - search
  - git-revision-date-localized:
      type: date
      locale: it
      enable_creation_date: true